# Generated by Django 3.2.23 on 2023-12-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identification_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='original_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='page_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('identification_no', models.IntegerField()),
                ('registration_no', models.IntegerField()),
                ('contact_no', models.CharField(max_length=14)),
                ('page_no', models.IntegerField()),
                ('original_address', models.CharField(max_length=50)),
                ('current_address', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('signature', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
