# Generated by Django 3.2.23 on 2023-12-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraries',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.faculty'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
        ),
        migrations.AddField(
            model_name='copies',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='Book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.faculty'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Book.language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Book.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Book.section'),
        ),
    ]
